version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Сохраняем изменения в коде в контейнере
      - ./sql_app.db:/app/sql_app.db  # Сохраняем базу данных на хосте
